{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "uptime-robot-operator.namespace" . }}
  labels:
    {{- include "uptime-robot-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}

