{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "uptime-robot-operator.fullname" . }}
  namespace: {{ include "uptime-robot-operator.namespace" . }}
  labels:
    {{- include "uptime-robot-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "uptime-robot-operator.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- $ingress := .Values.networkPolicy.ingress }}
  ingress:
    {{- if kindIs "slice" $ingress }}
    {{- toYaml $ingress | nindent 4 }}
    {{- else }}
    []
    {{- end }}
  {{- $egress := .Values.networkPolicy.egress }}
  egress:
    {{- if kindIs "slice" $egress }}
    {{- toYaml $egress | nindent 4 }}
    {{- else }}
    []
    {{- end }}
{{- end }}
