# This rule is not used by the project uptime-robot-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only permissions (get, list, and watch) over uptimerobot.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: uptime-robot-operator
    app.kubernetes.io/managed-by: kustomize
  name: maintenancewindow-viewer-role
rules:
- apiGroups:
  - uptimerobot.com
  resources:
  - maintenancewindows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - uptimerobot.com
  resources:
  - maintenancewindows/status
  verbs:
  - get
