## Append samples of your project ##
resources:
- uptime-robot_v1alpha1_secret.yaml
- uptime-robot_v1alpha1_account.yaml
- uptime-robot_v1alpha1_contact.yaml
- uptime-robot_v1alpha1_monitor.yaml
- uptime-robot_v1alpha1_monitor_dns.yaml
- uptime-robot_v1alpha1_monitor_heartbeat.yaml
- uptime-robot_v1alpha1_monitor_keyword.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
