---
apiVersion: uptimerobot.com/v1alpha1
kind: Monitor
metadata:
  labels:
    app.kubernetes.io/name: uptime-robot-operator
    app.kubernetes.io/managed-by: kustomize
  name: example-dns
spec:
  syncInterval: 5m  # How often operator syncs with UptimeRobot API
  prune: true
  monitor:
    name: Example DNS Monitor
    # For DNS monitors, set url to a hostname or IP (no scheme)
    url: dns.google.com
    type: DNS
    interval: 5m  # How often UptimeRobot checks the DNS
    dns:
      a:
        - "8.8.8.8"
        - "8.8.4.4"
    tags:
      - test
      - uptime-robot-operator
