---
apiVersion: uptimerobot.com/v1
kind: Monitor
metadata:
  labels:
    app.kubernetes.io/name: uptime-robot-operator
    app.kubernetes.io/managed-by: kustomize
  name: example-dns
spec:
  syncInterval: 5m  # How often operator syncs with UptimeRobot API
  prune: true
  monitor:
    name: Example DNS Monitor
    url: example.com
    type: DNS
    interval: 5m  # How often UptimeRobot checks the DNS
    dns:
      recordType: A
      value: "93.184.216.34"
